version: '3.8'

services:
  # Laravel Backend Service
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: laravel-backend
    container_name: laravel_backend
    restart: unless-stopped
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./server:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - db

  # Vue.js Frontend Service
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: vue-frontend
    container_name: vue_frontend
    restart: unless-stopped
    ports:
      - "8080:8080"

  # MySQL Database Service
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
